### PR TITLE
Add TVOS & OSX target in project and cocoapod podspec

### PR DESCRIPTION
**Pull request by phimage**
For carthage
- I edit "product name" of the two xcode project targets to "Then"
- I share the scheme

### CODE REVIEW

**Comment by devxoul** [comment]
@phimage, thanks for your work! Especially for podspec.

However, why do we need seperated targets?

**Comment by phimage** [comment]
For cocoapod no need to add targets

For xcode we need to test the compilation using the corresponding OS (even if there is no UIKit, Cocoa dependencies)
One target = one OS

And carthage use the shared scheme of target to compile for each OS (in separated folder)
Travis too use scheme, so you or I can edit .travis.yml to compil for each OS target/Scheme

**Comment by devxoul** [comment]
Scheme is already shared. For travis, I think this PR should have test code for each targets.

But actually I'm not sure separating target is necessary.

**Comment by phimage** [comment]
Test code for each target is not mandatory except complex codes or issue with 32/64 bits, many projects choose one OS to do unit tests

Ok you look for the more clean way to add other OS. Until know I see only project with multiples targets. If its the directories that bother you (ThenOSX, ThenTVOS) it's possible to remove them or regroup them (the requirements is that files must exist and added to targets, no matter where the files are)

**Comment by devxoul** [comment]
Oh, I mean the **`.travis.yml`** file. Apologize for unclear words. (For example, https://github.com/devxoul/SwiftyColor/blob/master/.travis.yml)

Exactly. I don't want to make directories for each targets. Well, how about [SwiftyJSON](https://github.com/SwiftyJSON/SwiftyJSON)'s approach? I think it seemed to be more clean :smile:

**Comment by phimage** [comment]
I do it
- share the header .h between the targets
- Move plist file into the unique folder Support and add in xcode a "group"
- 그럼 remove useless files and folders

**Comment by devxoul** [comment]
@phimage, thank you very much :smile::+1:

**Pull request merged**
